// components/Doctors/DoctorCard.tsx
import Image from "next/image";
import Link from "next/link";
import type { Doctor } from "@prisma/client";

/**
 * DoctorCard
 * - Takes a `Doctor` row straight from the database.
 *   That type is generated by Prisma from your schema, so if you add a column
 *   it appears here automatically — no separate type to keep in sync.
 * - Server Component friendly (no hooks)
 */
export default function DoctorCard({ doctor }: { doctor: Doctor }) {
  const { id, name, specialization, photoUrl, totalPatients, hospital, avgRating } = doctor;

  return (
    <section className="mx-auto w-11/12 my-14 px-5">
      <article className="max-w-[80%] mx-auto lg:px-0 lg:w-52.5 sm:w-100.75">
        <Image
          className="text-center rounded-md lg:h-[200px] lg:w-[210px]"
          src={photoUrl}
          alt={name}
          width={427}
          height={198}
          sizes="(max-width: 640px) 80vw, 427px"
        />

        <h2 className="font-bold text-gray-800 text-2xl mt-4">{name}</h2>

        <div className="flex items-center justify-between mt-3">
          <p className="bg-primaryLight font-bold text-primaryColor inline-block p-2 rounded-lg text-xs sm:text-xs">
            {specialization}
          </p>

          <p className="flex items-center text-xs gap-1 pr-2">
            <span>
              <Image src="/images/Star.png" alt="Rating star" width={16} height={16} className="w-[16px]" />
            </span>
            {avgRating}
          </p>
        </div>

        <div className="flex justify-between mt-3">
          <div>
            <h3 className="font-semibold text-gray-800 text-sm sm:text-base">+{totalPatients} Patients</h3>
            <p className="text-gray-800 sm:text-sm text-[0.7rem]">{hospital}</p>
          </div>

          <Link href={`/doctors/${id}`} className="w-[44px] h-[44px] flex items-start justify-end" aria-label="View doctor">
            
          </Link>
        </div>
      </article>
    </section>
  );
}
